import fs from 'node:fs/promises';
import path from 'node:path';
import { Router } from 'express';
import sharp from 'sharp';
import { prisma } from './db.js';
import { json, siteUrl } from './util.js';
import { standingsOf } from './routes/tournaments.js';

const router = Router();
const templates = new Map();
const esc = (v = '') => String(v).replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]);
const cut = (v, n = 180) => { const s = String(v || '').replace(/\s+/g, ' ').trim(); return s.length > n ? `${s.slice(0, n - 1)}…` : s; };
const abs = (p) => new URL(p, `${siteUrl()}/`).toString();
const fee = (v) => v ? (v / 100).toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' }) : 'Gratuito';
const when = (v) => new Intl.DateTimeFormat('pt-BR', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(v));

async function meta(kind, key) {
  if (kind === 'home') return { title: 'BX Deck Lab — Beyblade X competitivo', description: 'Monte decks, acompanhe o meta e participe da comunidade brasileira de Beyblade X.', url: abs('/'), image: abs('/og/home.png'), over: 'BORA RODAR PIÃO', head: 'BX DECK LAB', line: 'DECK BUILDER • META • COMUNIDADE', cta: 'MONTAR UM DECK', color: '#8ee83f' };
  if (kind === 'deck') {
    const d = await prisma.communityDeck.findUnique({ where: { slug: key }, include: { author: true } });
    if (!d || d.status !== 'VISIBLE' || !d.isPublic) return null;
    const beys = json(d.beysJson, []);
    return { title: `${d.title} — Deck da comunidade`, description: cut(d.description || `Deck público de ${d.author?.name || 'um blader'} no BX Deck Lab.`), url: abs(`/deck/${d.slug}`), image: abs(`/og/deck/${d.slug}.png`), over: 'DECK DA COMUNIDADE', head: d.title, line: `POR ${d.author?.name || 'COMUNIDADE'} • ${beys.length} BEYS • ${d.copyCount || 0} CÓPIAS`, cta: 'ABRIR DECK', color: '#48d7ff', art: 'deck', beys };
  }
  const t = await prisma.tournament.findUnique({ where: { slug: key }, include: { organizer: true, players: { include: { user: true, deck: true } }, matches: { include: { p1: { include: { user: true, deck: true } }, p2: { include: { user: true, deck: true } } } } } });
  if (!t || t.status === 'CANCELED') return null;
  const base = { url: abs(`/torneio/${t.slug}`), image: abs(`/og/tournament/${t.slug}.png`), head: t.name };
  if (t.status === 'FINISHED') { const rows = standingsOf(t).slice(0, 3); const pod = rows.map((x, i) => `${i + 1}º ${x.player.user.name}`).join(' • '); return { ...base, title: `${t.name} — resultado final`, description: cut(`Torneio encerrado. Classificação: ${pod || 'resultado disponível no BX Deck Lab.'}`), over: 'TORNEIO ENCERRADO', line: pod || 'RESULTADO FINAL DISPONÍVEL', cta: 'VER CLASSIFICAÇÃO', color: '#f2c94c', art: 'standings', rows }; }
  if (t.status === 'RUNNING') return { ...base, title: `${t.name} — em andamento`, description: `Rodada ${t.currentRound || 1} de ${t.roundsPlanned}. Acompanhe partidas e classificação.`, over: 'TORNEIO EM ANDAMENTO', line: `RODADA ${t.currentRound || 1}/${t.roundsPlanned} • ${t.players.length} JOGADORES`, cta: 'ACOMPANHAR TORNEIO', color: '#ff8b4b' };
  return { ...base, title: `${t.name} — inscrições abertas`, description: cut(`Inscrições abertas para ${when(t.startsAt)}${t.storeName ? ` em ${t.storeName}` : ''}. ${fee(t.entryFeeCents)}. Inscreva-se no BX Deck Lab.`), over: 'INSCRIÇÕES ABERTAS', line: `${when(t.startsAt).toUpperCase()} • ${fee(t.entryFeeCents).toUpperCase()} • ${t.players.length} INSCRITOS`, cta: 'INSCREVA-SE AGORA', color: '#8ee83f' };
}
function card(m) {
  const rings = (m.beys || [[], [], []]).slice(0, 3).map((b, i) => { const x = 765 + i * 135; const bits = (b || []).slice(0, 4).map((_, n) => `<circle cx="${x + Math.cos(n * 1.57) * 42}" cy="355" r="10" fill="${['#8ee83f','#48d7ff','#f2c94c','#ff8b4b'][n]}"/>`).join(''); return `<g><circle cx="${x}" cy="355" r="66" fill="#111b12" stroke="#8ee83f" stroke-width="5"/><circle cx="${x}" cy="355" r="47" fill="none" stroke="#48d7ff" stroke-width="9" stroke-dasharray="24 12"/><circle cx="${x}" cy="355" r="19" fill="#8ee83f"/>${bits}<text x="${x}" y="455" text-anchor="middle" fill="#dce8d7" font-family="Arial" font-size="14" font-weight="800">BEY ${i + 1}</text></g>`; }).join('');
  const standing = (m.rows || []).map((r, i) => `<g transform="translate(720 ${260 + i * 82})"><rect width="415" height="66" rx="12" fill="#111911" stroke="${i === 0 ? '#f2c94c' : '#2f4831'}"/><text x="25" y="43" fill="${i === 0 ? '#f2c94c' : '#8ee83f'}" font-family="Arial" font-size="26" font-weight="800">${i + 1}</text><text x="68" y="32" fill="#fff" font-family="Arial" font-size="19" font-weight="800">${esc(cut(r.player.user.name, 27))}</text><text x="68" y="53" fill="#9fb29e" font-family="Arial" font-size="13">${r.wins}V • ${r.losses}D</text><text x="378" y="42" text-anchor="end" fill="#fff" font-family="Arial" font-size="22" font-weight="800">${r.points} PTS</text></g>`).join('');
  const art = m.art === 'deck' ? rings : m.art === 'standings' ? standing : `<g opacity=".85"><circle cx="930" cy="355" r="128" fill="#101c10" stroke="${m.color}" stroke-width="8"/><circle cx="930" cy="355" r="86" fill="none" stroke="#48d7ff" stroke-width="15" stroke-dasharray="36 15"/><path d="M930 250v210M825 355h210" stroke="${m.color}" stroke-width="10"/></g>`;
  return `<svg width="1200" height="630" xmlns="http://www.w3.org/2000/svg"><defs><pattern id="grid" width="34" height="34" patternUnits="userSpaceOnUse"><path d="M34 0H0V34" fill="none" stroke="#8ee83f" stroke-opacity=".1"/></pattern><filter id="glow"><feGaussianBlur stdDeviation="8" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs><rect width="1200" height="630" fill="#080c09"/><rect width="1200" height="630" fill="url(#grid)"/><path d="M0 570Q310 410 620 580T1200 430V630H0Z" fill="#8ee83f" opacity=".11"/><rect x="50" y="46" width="1100" height="538" rx="24" fill="#0d140e" fill-opacity=".72" stroke="#355c38"/><text x="85" y="92" fill="#fff" font-family="Arial" font-size="26" font-weight="800">BX <tspan fill="#8ee83f">DECK LAB</tspan></text><text x="85" y="128" fill="${m.color}" font-family="Arial" font-size="17" font-weight="800" letter-spacing="3">${esc(m.over)}</text><text x="85" y="210" fill="#fff" font-family="Arial" font-size="51" font-weight="800">${esc(cut(m.head, 34))}</text><text x="85" y="257" fill="#b9c9b8" font-family="Arial" font-size="19">${esc(cut(m.line, 68))}</text><rect x="85" y="465" width="310" height="62" rx="12" fill="${m.color}" filter="url(#glow)"/><text x="240" y="504" text-anchor="middle" fill="#0b120b" font-family="Arial" font-size="18" font-weight="800">${esc(m.cta)}</text><text x="85" y="558" fill="#708870" font-family="Arial" font-size="14">beyxlab.com.br • BEYBLADE X COMPETITIVO</text>${art}</svg>`;
}
export async function sendSocial(res, file, m) { if (!m) return res.sendFile(path.resolve('public', file)); if (!templates.has(file)) templates.set(file, await fs.readFile(path.resolve('public', file), 'utf8')); const tags = `<title>${esc(m.title)}</title><meta name="description" content="${esc(m.description)}"><link rel="canonical" href="${esc(m.url)}"><meta property="og:type" content="website"><meta property="og:site_name" content="BX Deck Lab"><meta property="og:locale" content="pt_BR"><meta property="og:title" content="${esc(m.title)}"><meta property="og:description" content="${esc(m.description)}"><meta property="og:url" content="${esc(m.url)}"><meta property="og:image" content="${esc(m.image)}"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${esc(m.title)}"><meta name="twitter:description" content="${esc(m.description)}"><meta name="twitter:image" content="${esc(m.image)}">`; return res.type('html').send(templates.get(file).replace(/<title>[\s\S]*?<\/title>/i, '').replace('</head>', `${tags}</head>`)); }
const png = (kind) => async (req, res, next) => { try { const m = await meta(kind, req.params.slug); if (!m) return res.sendStatus(404); res.type('png').set('Cache-Control', 'public, max-age=300').send(await sharp(Buffer.from(card(m))).png().toBuffer()); } catch (e) { next(e); } };
router.get('/og/home.png', png('home')); router.get('/og/deck/:slug.png', png('deck')); router.get('/og/tournament/:slug.png', png('tournament'));
export { router as socialRouter, meta as socialMeta };
